### ISSUE TITLE
[types][Action, ComplexAction, etc] deprecate the depreacted `Button` boolean properties and add variant and tone support

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris#11040]
### Problem

Button variant boolean props were removed and replaced with stricter `variant` and `tone` props. Action objects passed into to various component props (e.g., `Page` or `Modal` `primaryAction`)  should match the Button API.

### Tasks
- [ ] Deprecate `DestructableAction` type (extends Action with `destructive` boolean property)
- [ ] Deprecate `PlainAction` type (extends Action with `plain` boolean property)
- [ ] Deprecate `OutlineableAction` type (extends Action with `outline` boolean property)

**Comment by jasperfurniss** [comment]
👋 Hey @chloerice and team! I'll grab this one! It'll be my first issue.
