### ISSUE TITLE
Answer questions on vault review for done

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris#12529]
```[tasklist]
### Tasks
- [ ] Do we have any merchant feedback about this?
- [ ] Have we finished cleaning up tech debt? What is left?
- [ ] How often are merchants using the page footer Save button vs. Top Bar?
- [ ] Are we in the driver's seat for holding teams with buggy forms accountable to fixing? Let's keep this review open until they are all addressed
- [ ] One thing I have found in my use of this feature to be annoying is 1. I make a form dirty 2. I try to nav away 3. Dirty state top bar prevents me 4. I click Discard 5. I have to re-try my attempt to nav away. Have we considered capturing the merchant's intent (nav destination) when showing the dirty state and executing on it when they click Discard?

```
